export const logementsData = [
  {
    id: 1,
    titre: "Logement n°3",
    description: "Duplex 70m², pour 4 personnes",
    caracteristiquesGenerales: [
      "Coin repos 5 places",
      "Coin salon",
      "TV BBox, 180 chaînes + WIFI",
      "Salle d'eau",
      "Sanitaires indépendantes",
    ],
    chambres: {
      nombreChambre: "2",
      chambre_1: ["2 lits jumeaux, 90cm/200cm", "1 lit individuel 90cm/200cm"],
      chambre_2: ["1 lit double 160cm/200cm"],
    },
    accesHandicape: true,
    appareilsElectromenagers: [
      "Lave-linge",
      "Réfrigérateur",
      "Plaque Vitro, 4 feux",
      "Four",
      "Lave-vaisselle",
      "Micro-ondes",
      "Cafetière",
    ],
    autresInformations: [
      "Animaux autorisés: Non",
      "Fumeurs autorisés: Non",
      "Wifi: Gratuit",
      "Parking: Gratuit",
    ],
    photos: ["", "", ""],
  },

  {
    id: 2,
    titre: "Logement n°4",
    description: "Duplex 75m², pour 5 personnes",
    caracteristiquesGenerales: [
      "Coin repos 6 places",
      "Coin salon",
      "Salle de bain",
    ],
    chambres: {
      nombreChambre: "3",
      chambre_1: ["1 lit individuel 90cm/200cm"],
      chambre_2: ["2 lits jumeaux 90cm/200cm"],
      chambre_3: ["1 lit double 140cm/190cm"],
    },
    accesHandicape: true,
    appareilsElectromenagers: [
      "Lave-linge en commun",
      "Réfrigérateur",
      "Four",
      "Lave-vaisselle",
      "Micro-ondes",
      "Cafetière",
    ],
    autresInformations: [
      "Animaux autorisés: Non",
      "Fumeurs autorisés: Non",
      "Wifi: Gratuit",
      "Parking: Gratuit",
    ],
    photos: [
      "images_logement/logement_4/lgt4_chambre_1.jpg",
      "images_logement/logement_4/lgt4_chambre_2.jpg",
      "images_logement/logement_4/lgt4_sejour.jpg",
      "images_logement/logement_4/lgt4_sdb.jpg",
    ],
  },
  {
    id: 3,
    titre: "Logement n°5",
    description: "Duplex 75m², pour 5 personnes",
    caracteristiquesGenerales: [
      "Coin repos 8 places",
      "Coin salon",
      "Salle de bain",
      "Climatisation",
    ],
    chambres: {
      nombreChambre: "1",
      chambre_1: ["1 lit individuel 90cm/190cm"],
      chambre_2: ["2 lits jumeaux 90cm/200cm"],
      chambre_3: ["1 lit double 140cm/190cm"],
    },
    accesHandicape: true,
    appareilsElectromenagers: [
      "Lave-linge",
      "Réfrigérateur",
      "Four",
      "Lave-vaisselle",
      "Micro-ondes",
      "Cafetière",
    ],
    autresInformations: [
      "Animaux autorisés: Non",
      "Fumeurs autorisés: Non",
      "Wifi: Gratuit",
      "Parking: Gratuit",
    ],
    photos: [
      "images_logement/logement_5/lgt5_chambre_1.jpg",
      "images_logement/logement_5/lgt5_chambre_2.jpg",
      "images_logement/logement_5/lgt5_chambre_3.jpg",
      "images_logement/logement_5/lgt5_chambre_4.jpg",
      "images_logement/logement_5/lgt5_sdb.jpg",
      "images_logement/logement_5/lgt5_sejour_1.jpg",
      "images_logement/logement_5/lgt5_sejour_2.jpg",
      "images_logement/logement_5/lgt5_sejour_3.jpg",
    ],
  },
  {
    id: 4,
    titre: "Logement n°6",
    description: "Suite 50m² avec terasse ouverte, pour 2/3 personnes",
    caracteristiquesGenerales: [
      "Coin repos 4 places",
      "Coin salon",
      "Canapé-lit",
      "TV BBox, 180 chaînes + WIFI",
      "Salle de bain",
      "Climatisation",
    ],
    chambres: {
      nombreChambre: "1",
      chambre_1: ["1 lit double 160cm/190cm"],
    },
    accesHandicape: true,
    appareilsElectromenagers: [
      "Lave-linge en commun",
      "Réfrigérateur",
      "Plaque Vitro, 4 feux",
      "Four",
      "Micro-ondes",
      "Cafetière",
    ],
    autresInformations: [
      "Animaux autorisés: Non",
      "Fumeurs autorisés: Non",
      "Wifi: Gratuit",
      "Parking: Gratuit",
    ],
    photos: ["images_logement/logement_6/lgt6_sejour.jpg"],
  },
  {
    id: 5,
    titre: "Logement n°7",
    description: "Suite 75m², pour 5 personnes",
    caracteristiquesGenerales: [
      "Coin repos 5 places",
      "Coin salon",
      "Canapé-lit",
      "TV BBox, 180 chaînes + WIFI",
      "Salle de bain",
    ],
    chambres: {
      nombreChambre: "3",
      chambre_1: ["1 lit double 160cm/200cm, 1 lit simple 90/190cm"],
      chambre_2: ["1 lit gigogne"],
      chambre_3: ["2 lits simples 90cm/190cm"],
    },
    accesHandicape: true,
    appareilsElectromenagers: [
      "Lave-linge en commun",
      "Réfrigérateur",
      "Plaque Vitro, 4 feux",
      "Four",
      "Micro-ondes",
      "Cafetière",
    ],
    autresInformations: [
      "Animaux autorisés: Non",
      "Fumeurs autorisés: Non",
      "Wifi: Gratuit",
      "Parking: Gratuit",
    ],
    photos: ["", "", ""],
  },
];
